
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x480")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 480,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)


canvas.create_rectangle(
    277.00000000000006,
    20.0,
    522.0,
    60.0,
    fill="#D5E8D4",
    outline="")

canvas.create_rectangle(
    209.00000000000006,
    440.0,
    591.0,
    470.0,
    fill="#D5E8D4",
    outline="")

canvas.create_text(
    277.00000000000006,
    20.0,
    anchor="nw",
    text="Smart Lysimeter",
    fill="#000000",
    font=("RobotoRoman Bold", 30 * -1)
)

canvas.create_rectangle(
    12.000000000000057,
    65.0,
    224.00000000000006,
    181.0,
    fill="#FFE6CC",
    outline="")

canvas.create_text(
    12.000000000000057,
    65.0,
    anchor="nw",
    text="Most Recent Data",
    fill="#000000",
    font=("RobotoRoman Bold", 20 * -1)
)

canvas.create_text(
    28.000000000000057,
    94.0,
    anchor="nw",
    text="pH: ",
    fill="#000000",
    font=("RobotoRoman Regular", 18 * -1)
)

canvas.create_text(
    28.000000000000057,
    123.0,
    anchor="nw",
    text="EC: ",
    fill="#000000",
    font=("RobotoRoman Regular", 18 * -1)
)

canvas.create_text(
    28.000000000000057,
    152.0,
    anchor="nw",
    text="Drainage Rate: ",
    fill="#000000",
    font=("RobotoRoman Regular", 18 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=12.000000000000057,
    y=190.0,
    width=212.0,
    height=30.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=12.000000000000057,
    y=230.0,
    width=212.0,
    height=30.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=12.000000000000057,
    y=270.0,
    width=212.0,
    height=30.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=12.000000000000057,
    y=310.0,
    width=212.0,
    height=30.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=12.000000000000057,
    y=350.0,
    width=212.0,
    height=30.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=12.000000000000057,
    y=390.0,
    width=212.0,
    height=30.0
)

canvas.create_text(
    219.00000000000006,
    440.0,
    anchor="nw",
    text="Date: 01/01/1970",
    fill="#000000",
    font=("RobotoRoman Bold", 22 * -1)
)

canvas.create_text(
    400.00000000000006,
    440.0,
    anchor="nw",
    text="Time: 00:00 AM",
    fill="#000000",
    font=("RobotoRoman Bold", 22 * -1)
)
window.resizable(False, False)
window.mainloop()
